### ISSUE TITLE
Honest Coach | Codeforces 1360 B

### ISSUE THREAD

**Issue by tejasbirsingh** [soorabsoni/Competitve-Programming#17]
I will provide the easiest solution for this problem. It uses a greedy technique along with sorting
Link:- https://codeforces.com/problemset/problem/1360/B
Things I will take care of:-

- Clean code with proper comments
- Time complexity explanation
- Samples test case explanation

Please assign this problem to me. Thanks

**Comment by soorabsoni** [comment]
Sure Tejasbir, you can add your code. We would be happy to accept your contribution!

**Comment by tejasbirsingh** [comment]
I have made a PR. Please check if it satisfies the standard. Thanks!
